### ISSUE TITLE
Add instructions on how to run in the README file

### ISSUE THREAD

**Issue by biltzerpos** [LePa-YU/ValidityChecker#1]
What the title says...

**Comment by annisiren** [comment]
How explicit should the instructions be? Should it be down to showing how to run a program in python for someone who doesn't know how to run a program in python or assuming the user will know how to execute the script but needs instructions to proceed from there?

**Comment by biltzerpos** [comment]
You can assume someone has installed python and knows how to use the command-line. It's mostly so it's clear which one is the main script to run.

**Comment by biltzerpos** [comment]
New version is better, but please add the command line one should use to run.

**Comment by biltzerpos** [comment]
Add the minimum requirement fo rPython version.
You can check whether tkinter is installed correctly with: python -m tkinter
Please update the README to say this first, and then redirect to instructions on how to install (it should not be necessary for anybody that has Python 3).

**Comment by annisiren** [comment]
Readme is updated.

**Comment by biltzerpos** [comment]
Great, closing.
