### ISSUE TITLE
The FAKE1001.csv file gives many whitespace errors

### ISSUE THREAD

**Issue by biltzerpos** [LePa-YU/ValidityChecker#2]
When I select the FAKE1001.csv file from the Datasets directory I get the following error dozens of times:

('ERROR: Please check that your csv header does not have extra whitespace before or after the terms listed. See: ', KeyError('type',))

This is supposed to be a well-formed input, so please investigate what causes this. The validity checker must be able to handle spaces in the csv file.

**Comment by annisiren** [comment]
This means that in the csv file there is empty space in the 'type' column header field. It's an error I inserted in there to prompt the user to format the headers properly before progressing.

**Comment by biltzerpos** [comment]
Following are the first two lines of FAKE1001.csv:

ID,Title,Alternative,targetUrl,Type,isPartOf,assesses,comesAfter
0,Start,start,,start,,,

It gives the error I mentioned above, even though there is no whitespace anywhere.

**Comment by annisiren** [comment]
Can you put this file in the datasets folder and I'll take a look?

**Comment by annisiren** [comment]
I added a header checker, wondering if it'll work for that file as well. It shouldn't give errors anymore, but I've only checked with the one dataset.

**Comment by biltzerpos** [comment]
I still get the same errors with the new version. The FAKE1001.csv file is in the Datasets repository. I'll let you manage the test datasets to be safe (you should have a few of them, as well as test cases that run automatically when changes have been made to the system :)

**Comment by annisiren** [comment]
type is spelled Type instead of type which leads to the error. The headers have to be well formed for it to work appropriately. I can always ignore case, and add it as an error, it really depends on how we want to approach the purpose of the validity checker. Should it be used to help format the data or is the primary purpose to just give a list of errors. E.g. the conversation about potentially modifying the dataset vs having the dataset modification happen manually.

**Comment by annisiren** [comment]
Note: the way the other dataset spells the headers is in accordance to DCMI, minus ID which should be identifier instead. I should probably change those as well but that would require more formatting in other places so I've left it for now.

E.g.             
ID,Title,Alternative,targetUrl,Type,isPartOf,assesses,comesAfter
should be
ID,title,alternative,targetUrl,type,assesses,comesAfter,alternativeContent,requires,isRequiredBy,isPartOf,isFormatOf

**Comment by biltzerpos** [comment]
The validity checker is only meant to provide errors and warnings, not to fix the data (kind of scary to change the data without human interaction). As such, the right way to deal with this issue to provide a warning (so a human can proceed to update their dataset if they want), but if ignoring case works then proceed by accepting this as the correct header.

**Comment by annisiren** [comment]
I think there's something wrong with the encoding of the FAKE.csv file. When I print out rows it gives me some random junk instead of the actual content that I see when I open it in a text editor. It works on all the other dataset files except the FAKE1001 file.

**Comment by annisiren** [comment]
Yup it was the encoding. I fixed it, but haven't pushed it yet. Do we want to assume that all the necessary header information is there aka all the fields exist? Or should this also be an error?

**Comment by biltzerpos** [comment]
At the moment, we have not specified a particular order for the fields, or what is the complete set of them (this may change anyway). So, the validity checker should not assume that all fields will be listed at the top. Non-mandatory ones can be omitted, which assumes that all their values are empty. Also, the order may be arbitrary.

**Comment by annisiren** [comment]
Currently order doesn't matter since it uses a dictionary type of data structure. However, it does require all of the fields to be present. I'll check for the presence of fields and give an error if the field isn't present (and then have the program proceed with the rest of the checks).

**Comment by biltzerpos** [comment]
A missing field should be a warning, not an error.

**Comment by annisiren** [comment]
I meant header/column is missing. You want those to also be just a warning?

**Comment by biltzerpos** [comment]
Yes, sorry I should have said header rather than field. To clarify, missing non-mandatory headers should generate a warning, mandatory ones an error. In the documentation, you should list what are the mandatory headers.

**Comment by annisiren** [comment]
Have we decided what those are concretely? Is this correct: ID, title, type, isPartOf (for atomic) and comesAfter (for composite). Are other fields mandatory?

**Comment by biltzerpos** [comment]
Let's go with just ID, title, type for now.

**Comment by biltzerpos** [comment]
Closing as this is now fixed.
