### ISSUE TITLE
Streamline output

### ISSUE THREAD

**Issue by biltzerpos** [LePa-YU/ValidityChecker#5]
A couple of things:

- Start with a message that says: "There were 4 errors, 5 warnings, and 456 missing fields."
- Print error -> Print errors, same for warnings.
- Missing columns should be one warning: "The following columns are missing: requires, isFormatOf etc..."
- Number the errors, warnings etc. so someone can refer to warning 35 or something.

**Comment by annisiren** [comment]
Fixed. Please verify. I added the same logic for missing fields as to headers to reduce the number of lines printed.

What do you mean by print error -> print errors?

**Comment by biltzerpos** [comment]
Just meant to make it plural. Go ahead and make that change as I won't be able to test before noon.

**Comment by annisiren** [comment]
> Just meant to make it plural. Go ahead and make that change as I won't be able to test before noon.

Done.

**Comment by biltzerpos** [comment]
Great job, only one more minor thing here: Instead of missing fields, let's call them empty fields. "Missing" sounds like something is wrong.

**Comment by annisiren** [comment]
Done.

**Comment by biltzerpos** [comment]
Also, when pressing f it still talks about Missing fields.

**Comment by annisiren** [comment]
That first one I definitely already fixed. Changed the second one now.

**Comment by biltzerpos** [comment]
Great, closing.
